[
    {
      "id": "1",
      "name": "Sự Lựa Chọn Của Phụ Nữ",
      "thumb_url": "https://img.ophim8.cc/uploads/movies/su-lua-chon-cua-phu-nu-thumb.jpg",
      "poster_url": "https://img.ophim8.cc/uploads/movies/su-lua-chon-cua-phu-nu-poster.jpg",
      "year": 2023,
      "status": true,
      "content": "Trong mắt người ngoài, Su Yu Ning gần như có một cuộc sống viên mãn: sự nghiệp phát đạt, người chồng hiền lành và cô con gái ngoan ngoãn. Thật bất ngờ, cuộc sống tuyệt vời này đã sụp đổ chỉ sau một đêm. Đầu tiên là chồng cô lừa dối, sau đó con gái cô bị thương và bất tỉnh. Chẳng mấy chốc, Su Yu Ning phát hiện ra rằng cô ấy đã là một phần của và ở giữa một âm mưu được tính toán. Và thứ cố thủ, ở trung tâm của âm mưu lại chính là người mà cô không bao giờ ngờ tới. Để bảo vệ con gái mình, Su Yu Ning đã phải đứng ra tuyên chiến với cô ta.",
      "category": "Tình cảm",
      "country": "Trung Quốc",
      "time": "15 phút",
      "link_embed": "https://vie2.opstream7.com/share/1ff8a7b5dc7a7d1f0ed65aaa29c04b1e"
    },
    {
      "id": "2",
      "name": "Thị Trưởng Kingstown (Phần 2)",
      "thumb_url": "https://img.ophim1.com/uploads/movies/mayor-of-kingstown-phan-2-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/mayor-of-kingstown-phan-2-poster.jpg",
      "year": 2023,
      "status": true,
      "content": "Cuộc tranh giành quyền lực trở nên gay go hơn bao giờ hết khi nhà McLusky cố gắng giữ trật tự ở mọi phía của cánh cổng.",
      "category": "Hình sự",
      "country": "Âu Mỹ",
      "time": "55 phút",
      "link_embed": "https://vie2.opstream7.com/share/65b9eea6e1cc6bb9f0cd2a47751a186f"
    },
    {
      "id": "3",
      "name": "VINLAND SAGA: Bản hùng ca Viking (Phần 2)",
      "thumb_url": "https://img.ophim1.com/uploads/movies/vinland-saga-ban-hung-ca-viking-phan-2-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/vinland-saga-ban-hung-ca-viking-phan-2-poster.jpg",
      "year": 2023,
      "status": true,
      "content": "Khi một thiên niên kỷ mới bắt đầu, Thorfinn vật lộn kiếm tìm ý nghĩa đời mình. Trong khi đó, vị vua mới của nước Anh tìm cách mở rộng lãnh thổ.",
      "category": "Hành động",
      "country": "Nhật Bản",
      "time": "29 phút",
      "link_embed": "https://kd.opstream3.com/share/7362b26d78069dd38f4b45743fddc7ee"
    },
    {
      "id": "4",
      "name": "Cô Ấy và Lời Nói Dối",
      "thumb_url": "https://img.ophim1.com/uploads/movies/co-ay-va-loi-noi-doi-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/co-ay-va-loi-noi-doi-poster.jpg",
      "year": 2010,
      "status": true,
      "content": "Zheng Xue Er, một phụ nữ mạnh mẽ với sự nghiệp thành công, không có kế hoạch kết hôn. Tuy nhiên, mẹ cô bị bệnh nặng, và để trấn an bà rằng bà sẽ tìm được một người chồng tử tế, Xue Er quyết định hạ thấp tiêu chuẩn chọn bạn đời và tìm một người lương thiện ổn định để kết hôn và sinh con càng sớm càng tốt. Dưới sự giới thiệu của người bạn thân Mi Li Li, cô gặp Tống Hạo Thiên và kết hôn với anh trong chớp nhoáng.Chẳng mấy chốc, mẹ cô qua đời và Zheng Xue Er nỗ lực để đạt được hạnh phúc trong gia đình nhỏ mới của mình. Sau khi kết hôn, Zheng Xue Er bị vô sinh vì lý do thể chất và mẹ chồng cô vô cùng không hài lòng về điều này. Nhưng kể cả khi cô mang thai thành công nhờ công nghệ ống nghiệm, thái độ của mẹ chồng đối với cô vẫn không hề cải thiện. Vẫn chưa đủ, phụ nữ sớm phát hiện ra rằng Hao Tian, người thích công khai yêu vợ, đã lừa dối cô với bạn của cô và cả hai lên kế hoạch chiếm đoạt tài sản của cô.Ban đầu, chỉ muốn bí mật điều tra chồng ngoại tình, Zheng Xue Er, khi biết rằng cái chết của mẹ cô cũng liên quan đến chồng cô, bị ám ảnh bởi sự cần thiết phải trả thù cho bà và trả giá cho tất cả những điều độc ác, hai người này đã làm đến cô, cô bắt đầu kế hoạch trả thù của mình.",
      "category": "Tình cảm",
      "country": "Trung Quốc",
      "time": "15 phút",
      "link_embed": "https://vie2.opstream7.com/share/4c56ff4ce4aaf9573aa5dff913df997a"
    },
    {
      "id": "5",
      "name": "Vương Quốc Tội Phạm",
      "thumb_url": "https://img.ophim1.com/uploads/movies/vuong-quoc-toi-pham-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/vuong-quoc-toi-pham-poster.jpg",
      "year": 2010,
      "status": true,
      "content": "Joshua “J” được đại gia đình nhận nuôi sau khi mẹ anh qua đời vì dùng thuốc quá liều. Gia tộc, được cai trị bởi bà nội đầy mưu mô của J, tham gia rất nhiều vào các hoạt động tội phạm, và J sớm bị truyền bá lối sống của họ. Nhưng J có cơ hội đi theo một con đường khác khi một cảnh sát tìm cách giúp đỡ anh ta.",
      "category": "Hình sự",
      "country": "Âu Mỹ",
      "time": "113 phút",
      "link_embed": "https://kd.opstream3.com/share/d347ad6d027270dec609d179e21995d4"
    },
    {
      "id": "6",
      "name": "ATM",
      "thumb_url": "https://img.ophim1.com/uploads/movies/atm-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/atm-poster.jpg",
      "year": 2012,
      "status": true,
      "content": "Sua và Jib giống như bất kỳ cặp đôi nào khác trên thế giới này, ngoại trừ một ngoại lệ: trong 5 năm qua họ đã giữ bí mật về mối quan hệ của mình vì ngân hàng nơi họ làm việc có chính sách nghiêm ngặt Không có tình thân. Đó không phải là vấn đề lớn cho đến khi họ quyết định kết hôn. Vấn đề duy nhất? Ai trong số hai người loại A này sẽ đặt hôn nhân lên trước sự nghiệp và từ chức? Cả hai đều không sẵn sàng thực hiện bước nhảy vọt về niềm tin, cả hai đều biến sự cố thành cơ hội khi một máy ATM trục trặc ở tỉnh Chonburi rút ra hơn 130.000 đô la baht.",
      "category": "Hài hước",
      "country": "Thái Lan",
      "time": "123 phút",
      "link_embed": "https://kd.opstream3.com/share/be61a669772d4f02117fa9c9ddc2a11a"
    },
    {
      "id": "7",
      "name": "Epic Movie",
      "thumb_url": "https://img.ophim1.com/uploads/movies/epic-movie-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/epic-movie-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Khi Edward, Peter, Lucy và Susan mỗi người đi theo con đường của riêng mình, cuối cùng họ thấy mình ở nhà máy Sôcôla của Willy. Đi qua tủ quần áo, họ phát hiện ra thế giới Gnarnia, nơi được cai trị bởi White Bitch. Gặp gỡ các nhân vật như Harry Potter và Thuyền trưởng Jack Swallows, gia đình mới đoàn tụ phải hợp tác với Aslo, một con sư tử khôn ngoan nhưng có sừng để ngăn chặn quân đội của chó cái trắng.",
      "category": "Hài hước",
      "country": "Âu Mỹ",
      "time": "85 phút",
      "link_embed": "https://kd.opstream3.com/share/feaa3aa9821868db73534710d1945c9c"
    },
    {
      "id": "8",
      "name": "Trọng Phạm",
      "thumb_url": "https://img.ophim1.com/uploads/movies/trong-pham-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/trong-pham-poster.jpg",
      "year": 2008,
      "status": true,
      "content": "Một người đàn ông trong gia đình bị kết tội giết kẻ đột nhập phải đối mặt với cuộc sống sau đó trong hệ thống hình phạt bạo lực.",
      "category": "Hành động",
      "country": "Âu Mỹ",
      "time": "103 phút",
      "link_embed": "https://kd.opstream3.com/share/b205ed537820cf30fd3012e805c7d9c6"
    },
    {
      "id": "9",
      "name": "Kiếm Sĩ Mù Xinh Đẹp",
      "thumb_url": "https://img.ophim1.com/uploads/movies/kiem-si-mu-xinh-dep-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/kiem-si-mu-xinh-dep-poster.jpg",
      "year": 2008,
      "status": true,
      "content": "Ichi là một nghệ sĩ mù đi du lịch khắp vùng nông thôn với cây đàn guitar truyền thống của Nhật Bản và cây gậy của cô ấy. Cô ấy đang tìm kiếm người đàn ông tốt bụng đã nuôi nấng cô ấy khi còn nhỏ, nhưng vì vẻ đẹp của mình mà cô ấy gặp phải vấn đề trên mọi bước đường. May mắn thay cho Ichi, cô ấy cũng là một nữ kiếm sĩ tài năng và mang theo một thanh kiếm sát thương bên trong chiếc gậy chống của mình.",
      "category": "Hành động",
      "country": "Nhật Bản",
      "time": "120 phút",
      "link_embed": "https://kd.opstream3.com/share/bd552ac73bbb7569413071a2661aab05"
    },
    {
      "id": "10",
      "name": " Ám Sát John F. Kennedy",
      "thumb_url": "https://img.ophim1.com/uploads/movies/am-sat-john-f-kennedy-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/am-sat-john-f-kennedy-poster.jpg",
      "year": 1991,
      "status": true,
      "content": "Theo dõi cuộc điều tra về vụ ám sát Tổng thống John F. Kennedy do luật sư quận New Orleans Jim Garrison dẫn đầu.",
      "category": "Chính kịch",
      "country": "Âu Mỹ",
      "time": "189 phút",
      "link_embed": "https://kd.opstream3.com/share/d28b6a4077491078708c95d4e8f35d68"
    },
    {
      "id": "11",
      "name": "Người Hùng Cuối Cùng",
      "thumb_url": "https://img.ophim1.com/uploads/movies/nguoi-hung-cuoi-cung-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/nguoi-hung-cuoi-cung-poster.jpg",
      "year": 1993,
      "status": true,
      "content": "Sau cái chết của cha mình, cậu bé Danny Madigan cảm thấy thoải mái khi xem những bộ phim hành động có cảnh sát bất khả chiến bại của Los Angeles Jack Slater. Sau khi được quản lý rạp chiếu phim Nick trao cho một chiếc vé ma thuật, Danny bị hút vào màn hình và gắn bó với Slater. Khi nhân vật phản diện hư cấu độc ác Benedict có trong tay chiếc vé và bước vào thế giới thực, Danny và Jack phải đi theo và ngăn chặn hắn.",
      "category": "Hành động",
      "country": "Âu Mỹ",
      "time": "131 phút",
      "link_embed": "https://kd.opstream3.com/share/3d194d58a6470121c92f29c1ee4c936f"
    },
    {
      "id": "12",
      "name": "Cặp Đôi Bất Đắc Dĩ",
      "thumb_url": "https://img.ophim1.com/uploads/movies/cap-doi-bat-dac-di-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/cap-doi-bat-dac-di-poster.jpg",
      "year": 1987,
      "status": true,
      "content": "Một giám đốc tiếp thị cáu kỉnh, Neal Page, đang trên đường về nhà ở Chicago để dự Lễ Tạ ơn khi một số sự chậm trễ buộc anh ta phải đi du lịch với một nhân viên bán rèm vòng tắm có ý tốt nhưng hống hách, Del Griffith.",
      "category": "Hài hước",
      "country": "Âu Mỹ",
      "time": "15 phút",
      "link_embed": "https://kd.opstream3.com/share/5de89937c146d16084648eea9295aa35"
    },
    {
      "id": "13",
      "name": "Revenge",
      "thumb_url": "https://img.ophim1.com/uploads/movies/revenge-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/revenge-poster.jpg",
      "year": 1990,
      "status": true,
      "content": "Michael ‘Jay’ Cochran vừa rời Hải quân sau 12 năm và anh ấy không chắc mình sẽ làm gì, ngoại trừ việc anh ấy biết mình muốn có một kỳ nghỉ. Anh quyết định đến thăm Tiburon Mendez, một doanh nhân người Mexico quyền lực nhưng mờ ám, người mà anh từng bay tới Alaska để đi săn. Đặt chân đến dinh thự của Mendez ở Mexico, anh lập tức bị bất ngờ bởi vẻ đẹp và sự trẻ trung của vợ Mendez, Miryea.",
      "category": "Tình cảm",
      "country": "Âu Mỹ",
      "time": "123 phút",
      "link_embed": "https://kd.opstream3.com/share/f142c6067e6345134c6728f299cf4c1e"
    },
    {
      "id": "14",
      "name": "Rambow Nhí",
      "thumb_url": "https://img.ophim1.com/uploads/movies/rambow-nhi-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/rambow-nhi-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Will đang tìm cách thoát khỏi gia đình thì gặp Lee, kẻ bắt nạt học đường. Được trang bị một máy quay video và một bản sao của Rambo, Lee dự định làm một video hoành tráng đầy hành động của riêng mình.",
      "category": "Hài hước",
      "country": "Âu Mỹ",
      "time": "96 phút",
      "link_embed": "https://kd.opstream3.com/share/073754d13ca65ee6903491686ed7c141"
    },
    {
      "id": "15",
      "name": "Điệu Nhảy Sôi Động",
      "thumb_url": "https://img.ophim1.com/uploads/movies/dieu-nhay-soi-dong-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/dieu-nhay-soi-dong-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Sau cái chết của em trai mình, một vũ công đường phố 19 tuổi rắc rối đến từ Los Angeles đã có thể vượt qua hội trường dành cho trẻ vị thành niên bằng cách đăng ký vào trường Đại học Truth lịch sử của người da đen ở Atlanta, Georgia. Nhưng những nỗ lực của anh ấy để có được một nền giáo dục và thu hút cô gái anh ấy thích đã bị gạt sang một bên khi anh ấy được hai hội anh em hàng đầu trong trường tán tỉnh, cả hai đều muốn và cần những bước nhảy theo phong cách đường phố khốc liệt của anh ấy để giành chiến thắng trong cuộc thi trình diễn bước đi quốc gia rất được thèm muốn.",
      "category": "Âm nhạc",
      "country": "Âu Mỹ",
      "time": "114 phút",
      "link_embed": "https://kd.opstream3.com/share/fda1e6e7b8c6a594746d60ff48746f12"
    },
    {
      "id": "16",
      "name": "400 Cú Đấm",
      "thumb_url": "https://img.ophim1.com/uploads/movies/400-cu-dam-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/400-cu-dam-poster.jpg",
      "year": 1959,
      "status": true,
      "content": "Cậu bé Antoine Doinel không thể tìm được sự đồng cảm ở trường hay ở nhà. Quyết định trốn chạy khỏi tất cả, Antoine ăn cắp máy đánh chữ của bố định bán lấy tiền. Nhưng cậu bị bắt gặp vào giao nộp cho cảnh sát, ngủ một đêm ở đồn cạnh những trộm cắp gái điếm. Những chuỗi ngày sau đó, từng mẩu chuyện về cuộc đời cô độc của cậu dần được hé lộ...",
      "category": "Chính kịch",
      "country": "Pháp",
      "time": "99 phút",
      "link_embed": "https://kd.opstream3.com/share/e37923cb28e2a3b2cc8a16e418b22612"
    },
    {
      "id": "17",
      "name": "The Experiment",
      "thumb_url": "https://img.ophim1.com/uploads/movies/the-experiment-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/the-experiment-poster.jpg",
      "year": 2001,
      "status": true,
      "content": "Das Experiment là một bộ phim kinh dị tâm lý gây sốc về tiềm năng tàn bạo mà con người che giấu. Điều gây sốc hơn nữa là nó dựa trên một sự kiện có thật - một thí nghiệm tâm lý năm 1971 tại Đại học Stanford đã bị hủy bỏ sớm khi những người làm thí nghiệm mất kiểm soát.",
      "category": "Chính kịch",
      "country": "Đức",
      "time": "120 phút",
      "link_embed": "https://kd.opstream3.com/share/165d6d6efc3c235ff0c042d3d8cfa8fd"
    },
    {
      "id": "18",
      "name": "Kẻ Đón Đường",
      "thumb_url": "https://img.ophim1.com/uploads/movies/ke-don-duong-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/ke-don-duong-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Khi đang lái xe qua sa mạc New Mexico trong một đêm mưa, các sinh viên đại học Jim Halsey và bạn gái của anh ấy là Grace Andrews đã nhờ người quá giang John Ryder. Khi ở trong xe của họ, kẻ lạ mặt tỏ ra là một kẻ tâm thần dùng dao đe dọa đôi vợ chồng trẻ, nhưng Jim đã thành công ném hắn ra khỏi xe trên đường. Sáng hôm sau, cặp vợ chồng trẻ nhìn thấy John trên một chiếc ô tô khác.",
      "category": "Hành động",
      "country": "Âu Mỹ",
      "time": "84 phút",
      "link_embed": "https://vie2.opstream7.com/share/1ff8a7b5dc7a7d1f0ed65aaa29c04b1e"
    },
    {
      "id": "19",
      "name": " Vũ Khí Sinh Học",
      "thumb_url": "https://img.ophim1.com/uploads/movies/vu-khi-sinh-hoc-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/vu-khi-sinh-hoc-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Nhà tâm lý học Carol Bennell của Washington, D.C. và đồng nghiệp của cô, Tiến sĩ Ben Driscoll là hai người duy nhất trên Trái đất biết về một dịch bệnh đang hoành hành khắp thành phố. Họ phát hiện ra một loại virus ngoài hành tinh trên một con tàu con thoi bị rơi có thể biến bất kỳ ai tiếp xúc với nó thành những chiếc máy bay không người lái khi họ đang ngủ. Carol nhận ra con trai mình đang nắm giữ chìa khóa để ngăn chặn sự lây lan của bệnh dịch hạch và cô chạy đua đi tìm con trai mình trước khi quá muộn.",
      "category": "Bí ẩn",
      "country": "Âu Mỹ",
      "time": "99 phút",
      "link_embed": "https://kd.opstream3.com/share/da03ec3df4a3182b2235d387e94b66cb"
    },
    {
      "id": "20",
      "name": "Ông Già Tuyết",
      "thumb_url": "https://img.ophim1.com/uploads/movies/ong-gia-tuyet-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/ong-gia-tuyet-poster.jpg",
      "year": 1994,
      "status": true,
      "content": "Vào đêm Giáng sinh, người cha đã ly hôn Scott Calvin và con trai phát hiện ra ông già Noel đã rơi khỏi mái nhà của họ. Khi Scott điều khiển chiếc xe trượt tuyết ma thuật, anh nhận ra mình giờ đã là ông già Noel mới và phải thuyết phục cả thế giới những kẻ không tin tưởng, bao gồm cả chính anh.",
      "category": "Hài hước",
      "country": "Âu Mỹ",
      "time": "97 phút",
      "link_embed": "https://kd.opstream3.com/share/baedb748044841999a16d08bbb7e7299"
    },
    {
      "id": "21",
      "name": "War",
      "thumb_url": "https://img.ophim1.com/uploads/movies/war-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/war-poster.jpg",
      "year": 2007,
      "status": true,
      "content": "Sau bộ phim “The One” đã lâu lắm rồi chúng ta mới thấy hai ngôi sao phim hành động là Lý Liên Kiệt (Jet Li) và Jason Statham - người nổi tiếng với series phim “The Transporter”; đóng cặp với nhau. Trở lại với bộ phim “War”, ở lần tái ngộ này Jason Statham trong vai một điệp viên FBI phải truy tìm một tên sát thủ với biệt danh là “Rouge” do Lý Liên Kiệt đóng. Đây là kẻ đã sát hại đồng nghiệp của anh và Jason Statham quyết bắt “Rouge” phải trả giá cho những hành động của mình…",
      "category": "Hành động",
      "country": "Âu Mỹ",
      "time": "103 phút",
      "link_embed": "https://kd.opstream3.com/share/1cdfddeb9a69434d800d17df7452ee5f"
    },
    {
      "id": "22",
      "name": "Chúng Tôi Từng Là Lính",
      "thumb_url": "https://img.ophim1.com/uploads/movies/chung-toi-tung-la-linh-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/chung-toi-tung-la-linh-poster.jpg",
      "year": 2002,
      "status": true,
      "content": "Câu chuyện về trận đánh lớn đầu tiên của giai đoạn chống Mỹ trong Chiến tranh Việt Nam và những người lính của cả hai bên tham chiến.",
      "category": "Hành động",
      "country": "Âu Mỹ",
      "time": "138 phút",
      "link_embed": "https://kd.opstream3.com/share/b19db9e093184a424038e07ab2ce8425"
    },
    {
      "id": "23",
      "name": "Kẻ phản diện lãng mạn",
      "thumb_url": "https://img.ophim1.com/uploads/movies/ke-phan-dien-lang-man-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/ke-phan-dien-lang-man-poster.jpg",
      "year": 2023,
      "status": true,
      "content": "Một câu chuyện về tuổi mới lớn và sự lãng mạn thực tế về những “nhân vật phản diện” trẻ ở trường đại học vẫn đang tìm hiểu về tình yêu. Kang Hee Jae rất muốn tỏ ra ngầu với người khác, nhưng thầm cảm thấy bên trong mình nhỏ bé hơn cả sinh vật phù du. Trong khi đấu tranh để tha thứ cho bạn gái của mình, Yoo Jin, vì hành vi “man rợ” của cô ấy, anh dần dần biến thành một con quái vật ám ảnh. Trong khi đó, Ban Yoo Jin là một sinh viên lớn tuổi rất thông minh tại trường đại học của Kang Hee Jae. Bởi vì Yoo Jin dường như không bao giờ có thể duy trì một mối quan hệ lâu hơn 100 ngày, cô ấy bắt đầu lo lắng rằng mình sẽ phải sống một cuộc đời cô đơn một mình. Vì vậy, khi học sinh nhỏ tuổi Hee Jae mạnh dạn thực hiện cú sút của mình, cô ấy quyết định đưa anh ấy qua một số “đào tạo” căng thẳng khi họ hẹn hò.",
      "category": "Hài hước",
      "country": "Hàn Quốc",
      "time": "45 phút",
      "link_embed": "https://vie2.opstream7.com/share/f457c545a9ded88f18ecee47145a72c0"
    },
    {
      "id": "24",
      "name": "Khu Vườn Dối Trá (Lời Nói Dối Ẩn Trong Khu Vườn)",
      "thumb_url": "https://img.ophim1.com/uploads/movies/khu-vuon-doi-tra-loi-noi-doi-an-trong-khu-vuon-thumb.jpg",
      "poster_url": "https://img.ophim1.com/uploads/movies/khu-vuon-doi-tra-loi-noi-doi-an-trong-khu-vuon-poster.jpg",
      "year": 2023,
      "status": true,
      "content": "Cuộc sống của một bà nội trợ bình thường đi theo một hướng bất ngờ sau khi nhận thấy một mùi lạ ở sân sau của cô ấy.",
      "category": "Hình sự",
      "country": "Hàn Quốc",
      "time": "55 phút",
      "link_embed": "https://1080.opstream4.com/share/2538ccba4cdbde6974a7a6a61c7d8f24"
    }
  ]